Repository qiniu/objc-sdk, pull requests merged in 2020-07, with the labels that each got.

#342 add the release badge
  README.md
Labels: lgtm

#344 Adjust badge
  README.md
Labels: size/XS

#343 adjust release badge
  README.md
Labels: size/XS

#347 dns local cache
  CHANGELOG.md
  Qiniu.podspec
  QiniuSDK.xcodeproj/project.pbxproj
  QiniuSDK/Http/Dns/QNDnsCacheFile.m
  QiniuSDK/Http/Dns/QNDnsCacheInfo.h
  QiniuSDK/Http/Dns/QNDnsCacheInfo.m
  QiniuSDK/Http/Dns/QNDnsCacheKey.h
  QiniuSDK/Http/Dns/QNDnsCacheKey.m
  QiniuSDK/Http/Dns/QNDnsPrefetcher.m
  QiniuSDK/Http/Dns/QNInetAddress.h
  QiniuSDK/Http/Dns/QNInetAddress.m
  QiniuSDK/Storage/QNConfiguration.m
  QiniuSDK/Utils/QNVersion.h
Labels: size/XL

#349 change version info
  README.md
Labels: size/XS
