Repository qiniu/objc-sdk, pull requests merged in 2020-09, with the labels that each got.

#362 handle memory problem
  CHANGELOG.md
  Qiniu.podspec
  QiniuDemo/QiniuDemo/ViewController.m
  QiniuSDK.xcodeproj/project.pbxproj
  QiniuSDK/Common/QNAutoZone.m
  QiniuSDK/Http/Dns/QNDnsPrefetch.m
  QiniuSDK/Http/QNResponseInfo.m
  QiniuSDK/Http/Request/HttpClient/UrlProtocol/QNCFHttpClient.m
  QiniuSDK/Http/Request/QNHttpRegionRequest.m
  QiniuSDK/Http/Request/QNHttpSingleRequest.m
  QiniuSDK/Http/Request/QNRequestTransaction.m
  QiniuSDK/Storage/QNBaseUpload.m
  QiniuSDK/Storage/QNConcurrentResumeUpload.m
  QiniuSDK/Storage/QNFormUpload.m
  QiniuSDK/Storage/QNResumeUpload.m
  QiniuSDK/Transaction/QNTransactionManager.m
  QiniuSDK/Utils/QNDefine.h
  QiniuSDK/Utils/QNDefine.m
  QiniuSDK/Utils/QNVersion.h
  QiniuSDKTests/QNFileRecorderTest.m
  README.md
Labels: size/L

#363 fix uplog fail
  CHANGELOG.md
  Qiniu.podspec
  QiniuSDK/Collect/QNReportConfig.m
  QiniuSDK/Collect/QNUploadInfoReporter.m
  QiniuSDK/Utils/QNVersion.h
  README.md
Labels: size/S

#364 change up log key and status_code logic
  QiniuSDK/Collect/QNReportItem.m
Labels: size/S

#365 up log quality add target_key and target_bucket
  QiniuSDK/Collect/QNReportItem.h
  QiniuSDK/Collect/QNReportItem.m
  QiniuSDK/Storage/QNUploadManager.m
Labels: size/S

#367 handle memory issue
  .travis.yml
  CHANGELOG.md
  Qiniu.podspec
  QiniuSDK/Collect/QNReportItem.m
  QiniuSDK/Http/QNResponseInfo.m
  QiniuSDK/Http/QNUploadRequestMetrics.h
  QiniuSDK/Http/QNUploadRequestMetrics.m
  QiniuSDK/Http/Request/HttpClient/QNUploadSystemClient.m
  QiniuSDK/Utils/QNVersion.h
  README.md
Labels: size/M

#368 Develop
  .travis.yml
  CHANGELOG.md
  Qiniu.podspec
  QiniuSDK/Collect/QNReportItem.h
  QiniuSDK/Collect/QNReportItem.m
  QiniuSDK/Http/QNResponseInfo.m
  QiniuSDK/Http/QNUploadRequestMetrics.h
  QiniuSDK/Http/QNUploadRequestMetrics.m
  QiniuSDK/Http/Request/HttpClient/QNUploadSystemClient.m
  QiniuSDK/Storage/QNUploadManager.m
  QiniuSDK/Utils/QNVersion.h
  README.md
Labels: size/M
